version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: proyecto-valorant-postgres-LA
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/postgres-valorant.sql:/docker-entrypoint-initdb.d/init.sql
  
  postgres:
    image: postgres:15
    container_name: proyecto-valorant-postgres-EU
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/postgres-valorant.sql:/docker-entrypoint-initdb.d/init.sql