postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    - ./init/postgres-valorant.sql:/docker-entrypoint-initdb.d/init.sql
