INSERT INTO rol (name) VALUES 
('Duelista'),
('Controlador'),
('Iniciador'),
('Centinela');
INSERT INTO maps (name) VALUES 
('Ascent'),
('Bind'),
('Breeze'),
('Fracture'),
('Haven'),
('Icebox'),
('Pearl'),
('Split'),
('Lotus'),
('Sunset'),
('Abyss');
INSERT INTO agents (name, role) VALUES 
('Brimstone', 2),
('Phoenix', 1),
('Sage', 4),
('Sova', 3),
('Viper', 2),
('Cypher', 4),
('Reyna', 1),
('Killjoy', 4),
('Breach', 3),
('Omen', 2),
('Jett', 1),
('Raze', 1),
('Skye', 3),
('Yoru', 1),
('Astra', 2),
('KAY/O', 3),
('Chamber', 4),
('Neon', 1),
('Fade', 3),
('Harbor', 2),
('Gekko', 3),
('Deadlock', 4),
('Iso', 1),
('Clove', 2),
('Vyse', 3);
INSERT INTO regions (name, code) VALUES 
('North America', 'NA'),
('Latin America', 'LA'),
('Brazil', 'BR'),
('Europe', 'EU'),
('Asia Pacific', 'AP'),
('Korea', 'KR');
INSERT INTO country (name, code) VALUES 
('United States', 'US'),
('Mexico', 'MX'),
('Brazil', 'BR'),
('Chile', 'CL'),
('Germany', 'DE'),
('France', 'FR'),
('Sweden', 'SE'),
('Turkey', 'TR'),
('United Kingdom', 'GB'),
('Poland', 'PL'),
('Spain', 'ES'),
('Bahrain', 'BH'),
('Hong Kong', 'HK'),
('Japan', 'JP'),
('Singapore', 'SG'),
('Australia', 'AU'),
('India', 'IN'),
('South Korea', 'KR');
