version: '3.8'

# TODO: Ver el puerto 55432, solo para master se cambio
services:
  postgres_primary:
    image: bitnami/postgresql:14
    container_name: proyecto-valorant-postgres-main
    ports:
      - "55432:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    volumes:
      - ./primary_data:/bitnami/postgresql
      - ./init/postgres-valorant.sql:/docker-entrypoint-initdb.d/init.sql

  postgres_replica_1:
    image: bitnami/postgresql:14
    container_name: proyecto-valorant-postgres-slave-1
    ports:
      - "5433:5432"
    depends_on:
      - postgres_primary
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_MASTER_HOST=postgres_primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    volumes:
      - ./replica1_data:/bitnami/postgresql

  postgres_replica_2:
    image: bitnami/postgresql:14
    container_name: proyecto-valorant-postgres-slave-2
    ports:
      - "5434:5432"
    depends_on:
      - postgres_primary
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_MASTER_HOST=postgres_primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    volumes:
      - ./replica2_data:/bitnami/postgresql

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: proyecto-valorant-postgres-exporter
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://user:password@postgres_primary:5432/postgres?sslmode=disable
    depends_on:
      - postgres_primary