version: '3.8'

services:
  mysql_master:
    image: mysql:8
    container_name: mysql_master
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: valorant
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=valorant
    volumes:
      - master_data:/var/lib/mysql
      - ./init/mysql-valorant.sql:/docker-entrypoint-initdb.d/init.sql

  mysql_slave1:
    image: mysql:8
    container_name: mysql_slave1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: valorant
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    command: --server-id=2 --relay-log=relay-log --log-bin=mysql-bin --read-only=1
    depends_on:
      - mysql_master
    volumes:
      - slave1_data:/var/lib/mysql

  mysql_slave2:
    image: mysql:8
    container_name: mysql_slave2
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: valorant
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    command: --server-id=3 --relay-log=relay-log --log-bin=mysql-bin --read-only=1
    depends_on:
      - mysql_master
    volumes:
      - slave2_data:/var/lib/mysql

volumes:
  master_data:
  slave1_data:
  slave2_data:
